project:
  name: Ozon Code Platform Est Water API
  environment: development

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

jaeger:
  service: est-water-api
  host: jaeger
  port: 6831

database:
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: est_water_api
  sslmode: disable
  migrations: migrations
  driver: pgx

telemetry:
  graylogPath: graylog:12201

logging:
  level: debug
  headerNameForRequestLevel: x-request-log-level
  headerNameForResponseLog: x-response-log-enabled