project:
  name: Ozon Code Platform Est Water API
  environment: development

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8080

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

jaeger:
  service: "est-water-api"
  host: "jaeger"
  port: ":6831"

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version

database:
  host: 0.0.0.0
  port: 5432
  user: docker
  password: docker
  name: est_water_api
  sslmode: disable
  migrations: migrations
  driver: pgx

kafka:
  capacity: 512
  topic: "est-water-events"
  groupId: "est-water-api"
  brokers:
    - "kafka:9092"
    - "localhost:9094"

telemetry:
  graylogPath: 0.0.0.0:12201

logging:
  level: "debug"
  headerNameForRequestLevel: "x-req-log-level"