version: "3.9"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    networks:
      - estnw
    links:
      - swagger-ui
      - est-water-api
      - pypi-server

  #traefik:
  #  image: traefik:latest
  #  restart: unless-stopped
  #  ports:
  #    - 8080:80
  #    - 8888:8080
  #  command:
  #    - "--api.insecure=true"
  #    - "--providers.docker=true"
  #    - "--providers.docker.exposedbydefault=false"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #  networks:
  #    - estnw

  est-water-api:
    build:
      context: .
      dockerfile: ./docker/est-water-api/Dockerfile
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: est-water-api
    networks:
      - estnw
    depends_on:
      - postgres
      - kafka
    links:
      - postgres
      - kafka
    ports:
      - 8083:8080 # REST
      - 8082:8082 # gRPC
      - 9100:9100 # Metrics prometheus
      - 8000:8000 # Status prometheus
      - 40000:40000 # Debug port
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8000/live']
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 20s
    volumes:
      - swaggerdata:/root/swagger
      - ./migrations:/root/migrations
      - ./config.yml:/root/config.yml
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.services.est-water-api.loadbalancer.healthcheck.scheme=http"
    #  - "traefik.http.services.est-water-api.loadbalancer.healthcheck.hostname=localhost"
    #  - "traefik.http.services.est-water-api.loadbalancer.healthcheck.port=8000"
    #  - "traefik.http.services.est-water-api.loadbalancer.healthcheck.path=/live"
    #  - "traefik.http.services.est-water-api.loadbalancer.healthcheck.interval=60s"
    #  - "traefik.http.services.est-water-api.loadbalancer.healthcheck.timeout=10s"
    #  - "traefik.http.routers.est-water-api.rule=PathPrefix(`/api`)"
    #  - "traefik.http.routers.est-water-api.middlewares=add-slash,strip-prefix-api"
    #  - "traefik.http.middlewares.add-slash.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
    #  - "traefik.http.middlewares.add-slash.redirectregex.replacement=$${1}/"
    #  - "traefik.http.middlewares.add-slash.redirectregex.permanent=true"
    #  - "traefik.http.middlewares.strip-prefix-api.stripprefix.prefixes=/api"
    #  - "traefik.http.services.est-water-api.loadbalancer.server.port=8080"

  retranslator:
    build:
      context: .
      dockerfile: ./docker/retranslator/Dockerfile
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: retranslator
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - estnw

  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: est_water_api
      APP_DB_USER: docker
      APP_DB_PASS: docker
      APP_DB_NAME: est_water_api
    networks:
      - estnw
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

  zookeeper:
    image: confluentinc/cp-zookeeper
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: zookeeper
    ports:
      - 2181:2181
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    networks:
      - estnw

  kafka:
    image: confluentinc/cp-kafka
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: kafka
    depends_on:
      - zookeeper
    ports:
      - 9094:9094
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:32181"
      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    command: sh -c "((sleep 15 && kafka-topics --create --zookeeper zookeeper:32181 --replication-factor 1 --partitions 1 --topic waters)&) && /etc/confluent/docker/run"
    networks:
      - estnw

  kafka-ui:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - 9001:9001
    environment:
      SERVER_PORT: 9001
      KAFKA_BROKERCONNECT: "kafka:9092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    networks:
      - estnw

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - 8081:8080
    restart: always
    volumes:
      - swaggerdata:/swagger
    environment:
      SWAGGER_JSON: /swagger/ozonmp/est_water_api/v1/est_water_api.swagger.json
    depends_on:
      - est-water-api
    networks:
      - estnw
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.routers.swagger-ui.rule=PathPrefix(`/swagger`)"
    #  - "traefik.http.routers.swagger-ui.middlewares=add-slash,strip-prefix-swagger"
    #  - "traefik.http.middlewares.add-slash.redirectregex.regex=^(https?://[^/]+/[a-z0-9_]+)$$"
    #  - "traefik.http.middlewares.add-slash.redirectregex.replacement=$${1}/"
    #  - "traefik.http.middlewares.add-slash.redirectregex.permanent=true"
    #  - "traefik.http.middlewares.strip-prefix-swagger.stripprefix.prefixes=/swagger"
    #  - "traefik.http.services.swagger-ui.loadbalancer.server.port=8080"

  jaeger:
    image: jaegertracing/all-in-one
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: jaeger
    ports:
      - 6831:6831/udp
      - 16686:16686
    networks:
      - estnw

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: prometheus
    ports:
      - 9090:9090
    extra_hosts:
      - "retranslator:host-gateway"
      - "est-water-api:host-gateway"
    networks:
      - estnw
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    links:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MYPASSWORT
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - estnw
    volumes:
      - ./docker/grafana/data:/var/lib/grafana
      - ./docker/grafana/provisioning:/etc/grafana/provisioning

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - estnw
    volumes:
      - esdata:/usr/share/elasticsearch/data
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html

  mongo:
    image: mongo:4.2
    restart: always
    networks:
      - estnw
    volumes:
      - mongodata:/data/db

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.0
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - estnw
    links:
      - mongo
      - elasticsearch
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    restart: always

  pypi-server:
    image: pypiserver/pypiserver:latest
    ports:
      - 8084:8080
    volumes:
      - ./pypkg:/data/packages
    command: -P . -a . /data/packages
    restart: always
    networks:
      - estnw

volumes:
  swaggerdata:
    driver: local
  pgdata:
    driver: local
  esdata:
    driver: local
  mongodata:
    driver: local

networks:
  estnw:
    driver: bridge
