global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'est-water-api'
    static_configs:
      - targets:
        - est-water-api:9100
  - job_name: 'retranslator'
    static_configs:
      - targets:
          - retranslator:9101