# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: ozonmp/est_water_api/v1/est_water_api.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import validate.validate_pb2
import google.api.annotations_pb2
import ozonmp.est_water_api.v1.est_water_api_pb2


class EstWaterApiServiceBase(abc.ABC):

    @abc.abstractmethod
    async def CreateWaterV1(self, stream: 'grpclib.server.Stream[ozonmp.est_water_api.v1.est_water_api_pb2.CreateWaterV1Request, ozonmp.est_water_api.v1.est_water_api_pb2.CreateWaterV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def DescribeWaterV1(self, stream: 'grpclib.server.Stream[ozonmp.est_water_api.v1.est_water_api_pb2.DescribeWaterV1Request, ozonmp.est_water_api.v1.est_water_api_pb2.DescribeWaterV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def ListWatersV1(self, stream: 'grpclib.server.Stream[ozonmp.est_water_api.v1.est_water_api_pb2.ListWatersV1Request, ozonmp.est_water_api.v1.est_water_api_pb2.ListWatersV1Response]') -> None:
        pass

    @abc.abstractmethod
    async def RemoveWaterV1(self, stream: 'grpclib.server.Stream[ozonmp.est_water_api.v1.est_water_api_pb2.RemoveWaterV1Request, ozonmp.est_water_api.v1.est_water_api_pb2.RemoveWaterV1Response]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ozonmp.est_water_api.v1.EstWaterApiService/CreateWaterV1': grpclib.const.Handler(
                self.CreateWaterV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.est_water_api.v1.est_water_api_pb2.CreateWaterV1Request,
                ozonmp.est_water_api.v1.est_water_api_pb2.CreateWaterV1Response,
            ),
            '/ozonmp.est_water_api.v1.EstWaterApiService/DescribeWaterV1': grpclib.const.Handler(
                self.DescribeWaterV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.est_water_api.v1.est_water_api_pb2.DescribeWaterV1Request,
                ozonmp.est_water_api.v1.est_water_api_pb2.DescribeWaterV1Response,
            ),
            '/ozonmp.est_water_api.v1.EstWaterApiService/ListWatersV1': grpclib.const.Handler(
                self.ListWatersV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.est_water_api.v1.est_water_api_pb2.ListWatersV1Request,
                ozonmp.est_water_api.v1.est_water_api_pb2.ListWatersV1Response,
            ),
            '/ozonmp.est_water_api.v1.EstWaterApiService/RemoveWaterV1': grpclib.const.Handler(
                self.RemoveWaterV1,
                grpclib.const.Cardinality.UNARY_UNARY,
                ozonmp.est_water_api.v1.est_water_api_pb2.RemoveWaterV1Request,
                ozonmp.est_water_api.v1.est_water_api_pb2.RemoveWaterV1Response,
            ),
        }


class EstWaterApiServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.CreateWaterV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.est_water_api.v1.EstWaterApiService/CreateWaterV1',
            ozonmp.est_water_api.v1.est_water_api_pb2.CreateWaterV1Request,
            ozonmp.est_water_api.v1.est_water_api_pb2.CreateWaterV1Response,
        )
        self.DescribeWaterV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.est_water_api.v1.EstWaterApiService/DescribeWaterV1',
            ozonmp.est_water_api.v1.est_water_api_pb2.DescribeWaterV1Request,
            ozonmp.est_water_api.v1.est_water_api_pb2.DescribeWaterV1Response,
        )
        self.ListWatersV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.est_water_api.v1.EstWaterApiService/ListWatersV1',
            ozonmp.est_water_api.v1.est_water_api_pb2.ListWatersV1Request,
            ozonmp.est_water_api.v1.est_water_api_pb2.ListWatersV1Response,
        )
        self.RemoveWaterV1 = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ozonmp.est_water_api.v1.EstWaterApiService/RemoveWaterV1',
            ozonmp.est_water_api.v1.est_water_api_pb2.RemoveWaterV1Request,
            ozonmp.est_water_api.v1.est_water_api_pb2.RemoveWaterV1Response,
        )
