{
 "title": "Est Water Api / Retranslator",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Кол-во NotFound",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "est_water_api_waters_not_found_total{job=\"est-water-api\"}"
    }
   ]
  },
  {
   "title": "Кол-во создаваемых CUD",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "est_water_api_waters_by_states_total{job=\"est-water-api\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Кол-во создаваемых CUD",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "est_water_api_waters_by_states_total{job=\"est-water-api\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Кол-во событий прошедших через рентраслятор",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "retranslator_waters_events_total{job=\"retranslator\"}"
    }
   ]
  },
  {
   "title": "Кол-во обрабатываемых событий в ретрансляторе",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "retranslator_waters_events_now_total{job=\"retranslator\"}",
     "legendFormat": "количество событий"
    }
   ]
  }
 ]
}